/*tslint:disable:max-line-length object-literal-sort-keys object-literal-key-quotes*/
const strings: {[key: string]: string | undefined} = {
    'action.resetZoom': 'Reset Zoom',
    'action.zoomIn': 'Zoom In',
    'action.zoomOut': 'Zoom Out',
    'action.edit': 'Edit',
    'action.view': 'View',
    'action.cut': 'Cut',
    'action.copy': 'Copy',
    'action.copyWithoutBBCode': 'Copy without BBCode',
    'action.paste': 'Paste',
    'action.copyLink': 'Copy Link',
    'action.incognito': 'Open in Incognito mode',
    'action.suggestions': 'Suggestions',
    'action.open': 'Show',
    'action.close': 'Close',
    'action.quit': 'Quit',
    'action.newWindow': 'Open new window',
    'action.newTab': 'Open new tab',
    'action.updateAvailable': 'Update available!',
    'action.cancel': 'Cancel',
    'action.bonus': 'Bonus',
    'action.logLevel': 'System log level',
    'action.toggleHighContrast': 'Disable Windows high-contrast mode',
    'action.profile': 'Show/hide current profile',
    'adEditor.title': 'Ad Editor',
    'adEditor.save': 'Save',
    'adEditor.moveUp': 'Move up',
    'adEditor.moveDown': 'Move down',
    'adEditor.remove': 'Remove ad',
    'adEditor.tags': "Enter one or more tags, e.g. 'romantic'",
    'adEditor.disable': 'Disable',
    'adEditor.another': 'Add Another',
    'adEditor.removeConfirm': 'Are you sure you wish to remove this ad?',
    'ads.post.title': 'Post Ads',
    'ads.post.start': 'Start Posting Ads',
    'ads.post.tagTitle': 'Ad Tags',
    'ads.post.desc': 'Serve ads that match any one of these tags:',
    'ads.post.target.title': 'Target Channels',
    'ads.post.target': 'Serve ads on these channels:',
    'ads.post.noChannels': 'You have no channels open that support ad posting. Open some channels first.',
    'ads.post.selectAll': 'Select/unselect all',
    'ads.post.order.title': 'Post Order',
    'ads.post.random': 'Random order',
    'ads.post.ordered': 'Follow order in Ad Center',
    'ads.post.campaign': 'Campaign',
    'ads.post.timeout': 'Timeout',
    'ads.post.used': ' ads will be used.',
    'ads.post.noAds': 'No ads to post!',
    'ads.post.create1': 'Use the ',
    'ads.post.adEditor': 'Ad Editor',
    'ads.post.create2': ' to create some ads first, then return here to post them.',
    'ads.post.minutes': 'minutes',
    'ads.post.hour': 'hour',
    'ads.post.hours': 'hours',
    'ads.post.alert.tag': 'Select at least one tag to post',
    'ads.post.alert.channel': 'Select at least one channel to post in',
    'ads.post.warn': 'Warning: This action will overwrite ads on channel {0}. Ads that are not stored in the Ad Center will be lost. Are you sure you wish to continue?',
    'admgr.postingBegins': 'Posting beings in {0}m {1}s',
    'admgr.nextPostDue': 'Next ad in {0}m {1}s',
    'admgr.expiresIn': ', auto-posting expires in {0}m {1}s',
    'admgr.noAds': 'No ads have been set up -- auto-posting will be cancelled. Click "Ads > Edit Channel Ads..." to set up your ads.',
    'admgr.activeHeader': 'Auto-Posting Ads',
    'admgr.comingNext': 'Coming Next',
    'admgr.renew': 'Renew',
    'admgr.setup': 'Set-Up Ads',
    'admgr.toggleAutoPost': 'Auto-Post Ads',
    'consoleWarning.head': 'THIS IS THE DANGER ZONE.',
    'consoleWarning.body': `ANYTHING YOU WRITE OR PASTE IN HERE COULD BE USED TO STEAL YOUR PASSWORDS OR TAKE OVER YOUR ENTIRE COMPUTER. This is where happiness goes to die. If you aren't a developer or a special kind of daredevil, please get out of here!`,
    'help': 'Help',
    'help.fchat': 'Frolic Help and Changelog',
    'help.feedback': 'Report a Bug / Suggest Something',
    'help.rules': 'F-List Rules',
    'help.faq': 'F-List FAQ',
    'help.report': 'How to report a user',
    'help.changelog': 'Changelog',
    'fs.error': 'Error writing to disk',
    'spellchecker.add': 'Add to Dictionary',
    'spellchecker.remove': 'Remove from Dictionary',
    'spellchecker.noCorrections': 'No corrections available',
    'window.newTab': 'New tab',
    'title': 'Frolic',
    'title.connected': 'Frolic ({0})',
    'version': 'Version {0}',
    'general.filter': 'Type to filter...',
    'general.loading': 'Loading...',
    'general.select': 'Select',
    'general.experiment': 'Experimental:',
    'general.feedback': 'Please provide feedback to Frolic developers about your 🚧 experiences!',
    'userlist.profile': 'Full Profile',
    'confirmYes': 'Yes',
    'confirmNo': 'No',
    'login.account': 'Username',
    'login.password': 'Password',
    'login.host': 'Host',
    'login.advanced': 'Show advanced settings',
    'login.save': 'Save login',
    'login.error': 'Error logging you in: Could not connect to server',
    'login.submit': 'Log in',
    'login.working': 'Logging in...',
    'login.selectCharacter': 'Select a character',
    'login.connect': 'Connect',
    'login.connecting': 'Connecting...',
    'login.connectError': 'Connection error: {0}',
    'login.alreadyLoggedIn': 'You are already logged in on this character in another tab or window.',
    'channelList.public': 'Official channels',
    'channelList.private': 'Open rooms',
    'channelList.create': 'Create room',
    'channelList.createName': 'Room name',
    'chat.logout': 'Log out',
    'chat.setStatus': 'Set status',
    'chat.setStatus.status': 'Status',
    'chat.setStatus.message': 'Status message (optional)',
    'chat.status.history': 'Status message history',
    'chat.status.history.none': 'This character has no status message history.',
    'chat.menu': 'Menu',
    'chat.recentConversations': 'Recent Conversations',
    'chat.adEditor': 'Ad Editor',
    'chat.postAds': 'Post Ads',
    'chat.stopAds': 'Stop All Ads',
    'chat.toggleAds': 'Toggle Ads',
    'chat.helper': 'Profile Helper',
    'chat.devTools': 'Frolic DevTools',
    'chat.channels': 'Channels',
    'chat.pms': 'PMs',
    'chat.newPM': 'Open Conversation',
    'chat.joinChannel': 'Join Channel',
    'chat.consoleTab': 'Console',
    'chat.pinTab': 'Pin this tab',
    'chat.closeTab': 'Close this tab',
    'charName.empty': 'Name must be longer.',
    'charName.space': 'Name cannot begin or end with a space.',
    'charName.invalid': 'Name contains invalid characters.',
    'charName.tooLong': "Name is too long.",
    'chat.confirmLeave': 'You are still connected to chat. Would you like to disconnect?',
    'chat.highlight': 'mentioned {0} in {1}:\n{2}',
    'chat.roll': 'rolls {0}: {1}',
    'chat.bottle': 'spins the bottle: {0}',
    'chat.consoleChat': 'You cannot chat here.',
    'chat.typing.typing': '{0} is typing...',
    'chat.typing.paused': '{0} has entered text.',
    'chat.errorOffline': '{0} is offline, you cannot send them a message right now.',
    'chat.errorIgnored': 'You are ignoring {0}. If you would like to send them a message, please unignore them first.',
    'chat.disconnected': 'You were disconnected from chat.\nAttempting to reconnect.',
    'chat.disconnected.title': 'Disconnected',
    'chat.ignoreList': 'You are currently ignoring: {0}',
    'chat.search': 'Search in messages...',
    'chat.send': 'Send',
    'chat.noBrowser': `Please configure a browser to use incognito mode.

Gear Menu -> Frolic -> Custom browser`,
    'chat.brokenBrowser': `Could not execute your chosen browser. Reassign your browser.

Gear Menu -> Frolic -> Custom browser`,
    'logs.title': 'Logs',
    'logs.character': 'Character',
    'logs.conversation': 'Conversation',
    'logs.confirmExport': 'Are you sure you would like to export all logs for {0}? If you have a lot of logs, this might take a while.',
    'logs.date': 'Date',
    'logs.selectCharacter': 'Select a character...',
    'logs.selectConversation': 'Select a conversation...',
    'logs.allDates': 'Show all',
    'logs.corruption.desktop': 'Log corruption has been detected. This is usually caused by a crash/force close or power loss mid-write. Please use the "Fix corrupted logs" option for this character to restore proper functionality.',
    'logs.corruption.mobile': 'Log corruption has been detected. This is usually caused by a crash/force close or power loss mid-write. Will now attempt to fix corrupted logs.',
    'logs.corruption.mobile.success': 'Your logs have been fixed.',
    'logs.corruption.mobile.error': 'Unable to fix corrupted logs. Please clear the application data or reinstall the app.',
    'logs.corruption.web': 'Error reading logs from browser storage. If this issue persists, please clear your stored browser data for F-Chat.',
    'logs.html': 'Would you like to export these logs as HTML with formatting? Otherwise, they will be exported as plain text.',
    'user.profile': 'Profile',
    'user.message': 'Open conversation',
    'user.messageJump': 'View conversation',
    'user.bookmark': 'Bookmark',
    'user.unbookmark': 'Unbookmark',
    'user.adLog': 'Show ad log',
    'user.ignore': 'Ignore',
    'user.unignore': 'Unignore',
    'user.hide': 'Hide ads',
    'user.unhide': 'Unhide ads',
    'user.memo': 'View memo',
    'user.memo.action': 'Update memo',
    'user.report': 'Report user',
    'user.channelKick': 'Kick from channel',
    'user.chatKick': 'Chat kick',
    'users.title': 'People',
    'users.friends': 'Friends',
    'users.bookmarks': 'Bookmarks',
    'users.members': 'Members',
    'users.memberCount': '{0} Members',
    'chat.report': 'Alert Staff',
    'chat.ads': 'Ads',
    'chat.memo': 'Memo',
    'chat.memoHeader': 'Memo:',
    'chat.report.description': `[color=red]Before you alert the moderators, PLEASE READ:[/color]
If you're just having personal trouble with someone, right-click their name and ignore them.
Please make sure what you're reporting is a violation of the site's [url=https://wiki.f-list.net/Code_of_Conduct]Code of Conduct[/url], otherwise nothing will be done.

This tool is intended for chat moderation. If you have a question, please visit our [url=https://wiki.f-list.net/Frequently_Asked_Questions]FAQ[/url] first, and if that doesn't help, join [session=Helpdesk]Helpdesk[/session] and ask your question there.

If your problem lies anywhere outside of the chat, please send in a Ticket instead.

For a more comprehensive guide as how and when to report another user, please [url=https://wiki.f-list.net/How_to_Report_a_User]consult this page.[/url]

Please provide a brief summary of your problem and the rules that have been violated.
[color=red]DO NOT PASTE LOGS INTO THE "REPORT TEXT" FIELD.
SELECT THE TAB YOU WISH TO REPORT, LOGS ARE AUTOMATICALLY ATTACHED[/color]`,
    'chat.report.fillIn': 'Please describe the incident.',
    'chat.report.conversation': 'Reporting tab',
    'chat.report.reporting': 'Reporting user',
    'chat.report.general': 'No one in particular. If you wish to report a specific user, please right-click them and select "Report".',
    'chat.report.text': 'Report text',
    'chat.report.convoWith': 'Conversation with {0}',
    'chat.report.reportingWho': 'Reporting user: [user]{0}[/user] | ',
    'settings.tabs.general': 'General',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.bonus': 'Misc.',
    'settings.tabs.filters': 'Chat filters',
    'settings.tabs.hideAds': 'Hidden users',
    'settings.tabs.import': 'Import',
    'settings.open': 'Settings',
    'settings.action': 'Change Settings',
    'settings.hideAds.empty': `You aren't currently hiding the ads of any users.`,
    'settings.import': 'Import Settings',
    'settings.import.selectCharacter': 'Select a character',
    'settings.import.confirm': `You are importing settings from your character {0}.
This will overwrite any and all settings, pinned conversations and conversation settings of character {1}.
Logs and recent conversations will not be touched.
You will be logged out. Once you log back in, the settings will have been imported.
Are you sure?`,
    'settings.playSound': 'Play notification sounds',
    'settings.notifications': 'Show desktop/push notifications',
    'settings.clickOpensMessage': 'Clicking users opens messages (instead of their profile)',
    'settings.enterSend': 'Enter sends messages (shows send button if disabled)',
    'settings.disallowedTags': 'Disallowed BBCode tags (comma-separated)',
    'settings.highlight': 'Notify for messages containing your name',
    'settings.highlightWords': 'Custom highlight notify words (comma-separated)',
    'settings.highlightUsersChannel': 'Allow usernames to match highlight words in this channel',
    'settings.showBroadcastsInPMs': 'Echo broadcasts in private messages',
    'settings.showAvatars': 'Show character avatars',
    'settings.animatedEicons': 'Animate [eicon]s',
    'settings.idleTimer': 'Idle timer (minutes, clear to disable)',
    'settings.messageSeparators': 'Display separators between messages',
    'settings.eventMessages': 'Display console messages (like login/logout, status changes) in current tab',
    'settings.joinMessages': 'Display join/leave messages in channels',
    'settings.joinMessageInThisChannel': 'Display join/leave messages',
    'settings.alwaysNotify': 'Play sounds even when looking at the tab',
    'settings.friendSignIn': 'Notify when friends or bookmarks sign in',
    'settings.friendMessageNotification': 'Notify when friends or bookmarks send a message in channels',
    'settings.friendMessageInThisChannel': 'Notify when friends or bookmarks send a message',
    'settings.closeToTray': 'Close to tray',
    'settings.spellcheck': 'Spellcheck',
    'settings.spellcheck.disabled': 'Disabled',
    'settings.theme': 'Theme',
    'settings.profileViewer': 'Use profile viewer',
    'settings.logDir': 'Change log location',
    'settings.logDir.confirm': `Do you want to set your log location to {0}?

No files will be moved. If you click Yes here, Frolic will shut down. If you would like to keep your log files, please move them manually before restarting Frolic.

Current log location: {1}`,
    'settings.logDir.inAppDir': 'Please set your log directory to a location outside of the Frolic installation directory, as it would otherwise be overwritten during an update.',
    'settings.logMessages': 'Log messages',
    'settings.logAds': 'Log ads',
    'settings.fontSize': 'Font size',
    'settings.showNeedsReply': 'Show indicator on PM tabs with unanswered messages',
    'settings.defaultHighlights': 'Use global highlight words',
    'settings.useGlobalSetting': 'Use global setting',
    'settings.colorBookmarks': 'Show friends/bookmarks in a different colour',
    'settings.beta': 'Opt-in to test unstable prerelease updates',
    'settings.hwAcceleration': 'Enable hardware acceleration (requires restart)',
    'settings.bbCodeBar': 'Show BBCode formatting bar',
    'settings.browser': 'Custom browser',
    'settings.browser.header': 'Browser Settings',
    'settings.browser.title': 'Custom Browser',
    'settings.browser.warning.title': '⚠ Danger Zone! ⚠',
    'settings.browser.warning.msg': 'This is an advanced setting. By changing this setting to an unsupported program (i.e. not a browser), you might not be able to open links from Frolic anymore.',
    'settings.browser.warning.mac1': 'Mac User: MacOS has a bug in how it handles opening links.',
    'settings.browser.warning.mac2': 'When your default system browser is something other than Safari and you select Safari as your custom browser, links might open twice - once in Safari and again in your chosen browser.',
    'settings.browser.warning.mac3': 'This tends to happen when Safari is not running when clicking a link.',
    'settings.browser.path': 'Path to browser executable',
    'settings.browser.default': 'System default',
    'settings.browser.arguments': 'Arguments to pass to executable',
    'settings.browser.argumentsHelp': 'Arguments are separated by spaces. Use %s to insert the URL.',
    'settings.browser.browse': 'Browse',
    'settings.browser.current': 'Current: ',
    'settings.browser.save': 'Save',
    'settings.browser.reset': 'Reset to default',
    'settings.browser.incognito.title': 'Incognito Mode',
    'settings.browser.incognito.help': 'Command-line argument for "right click -> Open in Incognito mode"',
    'settings.browser.incognito.auto': 'Detect',
    'settings.browser.incognito.auto.warning': 'No known incognito mode for this browser.',
    'fixLogs.action': 'Fix corrupted logs',
    'fixLogs.text': `There are a few reason log files can become corrupted - log files from old versions with bugs that have since been fixed or incomplete file operations caused by computer crashes are the most common.
If one of your log files is corrupted, you may get an "Unknown Type" error when you log in or when you open a specific tab. You may also experience other issues.
This is not a tool you should use if you're not sure it's absolutely necessary. It will go through and rewrite all of your log files.
Once this process has started, do not interrupt it or your logs will get corrupted even worse.`,
    'fixLogs.character': 'Character',
    'fixLogs.error': 'An error has occurred while attempting to fix your logs. Please ask in for further assistance in the Helpdesk channel.',
    'fixLogs.success': 'Your logs have been fixed. If you experience any more issues, please ask in for further assistance in the Helpdesk channel.',
    'conversationSettings.title': 'Tab Settings',
    'conversationSettings.action': 'Edit settings for {0}',
    'conversationSettings.save': 'Save settings',
    'conversationSettings.default': 'Default',
    'conversationSettings.true': 'Yes',
    'conversationSettings.false': 'No',
    'conversationSettings.notify': 'Notify for messages',
    'conversationSettings.friendsOnly': 'Friends only',
    'conversationSettings.bookmarksOnly': 'Bookmarks only',
    'conversationSettings.friendsAndBookmarks': 'Friends and bookmarks',
    'conversationSettings.noOne': 'No one',
    'general.console': 'Console',
    'general.ellipses': '...',
    'general.history': 'History',
    'general.name': 'Name',
    'general.open': 'Open',
    'channel.mode.title': 'View',
    'channel.mode.ads': 'Ads',
    'channel.mode.chat': 'Chat',
    'channel.mode.both': 'Both',
    'channel.mode.ads.countdown': 'Ads ({0}m{1}s)',
    'channel.ads.start': 'Start',
    'channel.ads.pause': 'Pause',
    'channel.ads.posting': 'Posting Ads',
    'channel.ads.edit': 'Edit Channel Ads...',
    'channel.ads.incompatible': 'Show Incompatible Ads',
    'channel.official': 'Official channel',
    'channel.description': 'Description',
    'manageChannel.open': 'Manage',
    'manageChannel.action': 'Manage {0}',
    'manageChannel.submit': 'Save settings',
    'manageChannel.mods': 'Channel moderators',
    'manageChannel.modAdd': 'Add moderator',
    'manageChannel.modAddName': 'New moderator name',
    'manageChannel.isPublic': 'Is public (i.e. in the channel list; anyone can join without an invite)',
    'manageChannel.mode': 'Allowed messages',
    'manageChannel.description': 'Description',
    'characterAds.title': 'Channel Ads for ',
    'characterAds.none': ' has not posted any ads in the channels you are in.',
    'characterChannels.title': 'Channels for ',
    'characterChannels.none': ' is not on any of the channels you are on.',
    'characterPreview.perfect': 'Unicorn',
    'characterPreview.yearsOld': '{0} years old ',
    'characterPreview.memo': 'Memo',
    'characterPreview.status': 'Status',
    'characterPreview.status2': '& Latest Ad',
    'characterPreview.messages': 'Latest Messages',
    'characterPreview.ad': 'Latest Ad',
    'characterSearch.open': 'Character Search',
    'characterSearch.history': 'History',
    'characterSearch.reset': 'Reset',
    'characterSearch.update': 'Update',
    'characterSearch.action': 'Search Characters',
    'characterSearch.pending': 'Searching for',
    'characterSearch.scoring': 'Scoring {0}...',
    'characterSearch.searching': 'Searching...',
    'characterSearch.again': 'Start another search',
    'characterSearch.results': '{0} Results',
    'characterSearch.kinks': 'Kinks',
    'characterSearch.genders': 'Genders',
    'characterSearch.orientations': 'Orientations',
    'characterSearch.languages': 'Languages',
    'characterSearch.furryprefs': 'Furry preferences',
    'characterSearch.roles': 'Dom/sub roles',
    'characterSearch.positions': 'Positions',
    'characterSearch.species': 'Species (beta)',
    'characterSearch.bodytypes': 'Body types',
    'characterSearch.error.noResults': 'There were no search results.',
    'characterSearch.error.throttle': 'You must wait five seconds between searches.',
    'characterSearch.error.tooManyResults': 'There are too many search results, please narrow your search.',
    'characterSearch.noHistory': 'This character has no search history.',
    'characterSearch.searchHistory': 'Search history',
    'characterSearch.select': 'Select',
    'profile.edit': 'Edit',
    'profile.delete': 'Delete',
    'profile.duplicate': 'Duplicate',
    'profile.addFriend': 'Friend',
    'profile.report': 'Report',
    'profile.sendNote': 'Send Note',
    'profile.online': 'Online in Chat',
    'profile.created': 'Created',
    'profile.updated': 'Last Updated',
    'profile.lastOnline': 'Last Online',
    'profile.views': 'Views',
    'profile.timezone': 'Timezone',
    'profile.timeInUTC': 'UTC{0}{1}',
    'events.broadcast': '{0} has broadcast: {1}',
    'events.broadcast.notification': 'Broadcast from {0}',
    'events.invite': '{0} has invited you to join {1}',
    'events.error': 'Error: {0}',
    'events.rtbCommentReply': '{0} replied to your comment on the {1}: {2}',
    'events.rtbComment': '{0} commented on your {1}: {2}',
    'events.rtbComment_bugreport': 'bug report',
    'events.rtbComment_changelog': 'changelog post',
    'events.rtbComment_feature': 'feature request',
    'events.rtbComment_newspost': 'news post',
    'events.rtb_note': '{0} has sent you a note: {1}',
    'events.rtb_bugreport': '{0} submitted a bug report: {1}',
    'events.rtb_featurerequest': '{0} submitted a feature request: {1}',
    'events.rtb_grouprequest': '{0} requested a group named: {1}',
    'events.rtb_helpdeskreply': '{0} replied to [url={1}]a help desk ticket you are involved in[/url].',
    'events.rtb_helpdeskticket': '{0} submitted a help desk ticket: {1}',
    'events.rtb_friendrequest': '{0} has sent you a friend request.',
    'events.report': '[b][color=red]MODERATOR ALERT[/color][/b] - Report by {0}:\nCurrent tab: {1}\nReport: {2}',
    'events.report.confirmed': '{0} is handling {1}\'s report.',
    'events.report.confirm': 'Confirm report',
    'events.report.viewLog': 'View log',
    'events.report.noLog': 'No log available',
    'events.status': '{0} is now {1}.',
    'events.status.message': '{0} is now {1}: {2}',
    'events.status.own': 'You are now {0}.',
    'events.status.ownMessage': 'You are now {0}: {1}',
    'events.ban': '{2} has banned {1} from {0}.',
    'events.timeout': '{2} has timed out {1} from {0} for {3} minutes.',
    'events.kick': '{2} has kicked {1} from {0}.',
    'events.login': '{0} has logged in.',
    'events.logout': '{0} has logged out.',
    'events.channelJoin': '{0} has joined the channel.',
    'events.channelLeave': '{0} has left the channel.',
    'events.ignore_add': 'You are now ignoring {0}\'s messages. Should they go around this by any means, please report it using the Alert Staff button.',
    'events.ignore_delete': '{0} is now allowed to send you messages again.',
    'events.uptime': 'Server has been running since {0}, with currently {1} channels and {2} users, a total of {3} accepted connections, and {4} maximum users.',
    'events.highlight': '{0} said "{1}" in {2}',
    'preview.debug': 'Debug Mode',
    'preview.expand': 'Expand Images',
    'preview.reload': 'Reload Image',
    'preview.reset': 'Reset Image Viewer',
    'preview.sticky': 'Toggle Stickiness',
    'commands.unknown': 'Unknown command. For a list of valid commands, please click the ? button.',
    'commands.badContext': 'This command cannot be used here. Please use the Help (click the ? button) if you need further information.',
    'commands.tooFewParams': 'This command requires more parameters. Please use the Help (click the ? button) if you need further information.',
    'commands.invalidParam': 'The value for the parameter {0} is invalid. Please use the Help (click the ? button) if you need further information.',
    'commands.invalidCharacter': 'The character you entered is not online. Put the name in double quotes if you want to override. Please use the Help (click the ? button) if you need further information.',
    'commands.help': 'Command Help',
    'commands.help.syntax': 'Syntax: {0}',
    'commands.help.contextChannel': 'This command can be executed in a channel tab.',
    'commands.help.contextPrivate': 'This command can be executed in a private conversation tab.',
    'commands.help.contextConsole': 'This command can be executed in the console tab.',
    'commands.help.permissionRoomOp': 'This command requires you to be an operator in the selected channel.',
    'commands.help.permissionRoomOwner': 'This command requires you to be the owner of the selected channel.',
    'commands.help.permissionChannelMod': 'This command requires you to be an official channel moderator.',
    'commands.help.permissionChatOp': 'This command requires you to be a global chat operator.',
    'commands.help.permissionAdmin': 'This command requires you to be an admin.',
    'commands.help.parameters': 'Parameters:',
    'commands.help.paramOptional': '{0} (optional):',
    'commands.param_character': 'Character',
    'commands.param_character.help': 'The name of a character. Must be valid and logged in - override by putting in double quotes.',
    'commands.reward': 'Reward',
    'commands.reward.help': 'Reward a user, giving them a special status until they change it or log out.',
    'commands.greports': 'Pending reports',
    'commands.greports.help': 'Requests a list of pending chat reports from the server.',
    'commands.join': 'Join channel',
    'commands.join.help': 'Joins the channel with the given name/ID.',
    'commands.join.param0': 'Channel ID',
    'commands.join.param0.help': 'The name/ID of the channel to join. For official channels, this is the name, for private rooms this is the ID.',
    'commands.close': 'Close tab',
    'commands.close.help': 'Closes the currently viewed PM or channel tab.',
    'commands.clear': 'Clear tab',
    'commands.clear.help': 'Clears the currently viewed tab, emptying its message list. No logs will be deleted.',
    'commands.uptime': 'Uptime',
    'commands.uptime.help': 'Requests statistics about server uptime.',
    'commands.status': 'Set status',
    'commands.status.help': 'Sets your status along with an optional message.',
    'commands.status.param0': 'Status',
    'commands.status.param0.help': 'A valid status, namely "online", "busy", "looking", "away" or "dnd".',
    'commands.status.param1': 'Message',
    'commands.status.param1.help': 'An optional status message of up to 255 bytes.',
    'commands.priv': 'Open conversation',
    'commands.priv.help': 'Opens a conversation with the given character.',
    'commands.broadcast': 'Chat broadcast',
    'commands.broadcast.help': 'Broadcast a message, alerting all currently connected characters.',
    'commands.broadcast.param0': 'Message',
    'commands.broadcast.param0.help': 'Broadcast message. May contain valid chat BBCode.',
    'commands.makeroom': 'Create private room',
    'commands.makeroom.help': 'Creates a private room. Only people you /invite will be able to join it, and it will not be listed, until you open it with /openroom.',
    'commands.makeroom.param0': 'Room name',
    'commands.makeroom.param0.help': 'A name for your new private room. Must be 1-64 in length.',
    'commands.ignore': 'Ignore a character',
    'commands.ignore.help': 'Ignores the given character, and discards all of their messages, except in channels where you are a moderator.',
    'commands.unignore': 'Unignore a character',
    'commands.unignore.help': 'Removes the given character from your ignore list, and allows them to send you messages again.',
    'commands.ignorelist': 'Ignore list',
    'commands.ignorelist.help': 'Lists all of the characters currently on your ignore list.',
    'commands.roll': 'Dice roll',
    'commands.roll.help': 'Rolls dice (RNG), displaying the result to all members of the current tab.',
    'commands.roll.param0': 'Dice',
    'commands.roll.param0.help': 'Syntax: [1-9]d[1-100]. Addition and subtraction of rolls and fixed numbers is also possible. Example: /roll 1d6+1d20-5',
    'commands.bottle': 'Spin the bottle',
    'commands.bottle.help': 'Spins a bottle, randomly selecting a member of the current tab and displaying it to all.',
    'commands.me': 'Post as action',
    'commands.me.help': 'This will cause your message to be formatted differently, as an action your character is performing.',
    'commands.me.param0': 'Message',
    'commands.me.param0.help': 'The message to post as an action - the action you would like your character to perform.',
    'commands.warn': 'Warn channel',
    'commands.warn.help': 'Provides a way for channel moderators to warn/alert members. This message will be formatted differently, and is often used as a warning before moderator action.',
    'commands.warn.param0': 'Message',
    'commands.warn.param0.help': 'The message to post as a warning.',
    'commands.kick': 'Channel kick',
    'commands.kick.help': 'Removes a character from the current channel. They are free to rejoin - use /ban or /timeout if you want to get rid of them for a longer period of time.',
    'commands.ban': 'Channel ban',
    'commands.ban.help': 'Bans a character from the current channel. They will not be able to rejoin unless and until you undo this with /unban.',
    'commands.unban': 'Channel unban',
    'commands.unban.help': 'Unbans a character from the current channel, allowing them to rejoin.',
    'commands.banlist': 'Channel ban list',
    'commands.banlist.help': 'Requests the ban list for the current channel. The server will reply with a system response, which you will be able to view in the Console tab.',
    'commands.timeout': 'Channel timeout',
    'commands.timeout.help': 'Temporarily bans the given character from the current channel. Mind the comma in the syntax!',
    'commands.timeout.param1': 'Duration',
    'commands.timeout.param1.help': 'The number of minutes to ban the character for.',
    'commands.op': 'Promote to Channel OP',
    'commands.op.help': 'Promotes a character to channel OP in the current channel.',
    'commands.deop': 'Demote from Channel OP',
    'commands.deop.help': 'Demotes a character from channel OP in the current channel.',
    'commands.oplist': 'List Channel OPs',
    'commands.oplist.help': 'Lists all the OPs of the current channel.',
    'commands.setowner': 'Set channel owner',
    'commands.setowner.help': 'Set the owner of a channel to another character. The previous owner will be demoted to a member.',
    'commands.invite': 'Invite to room',
    'commands.invite.help': 'Invites a character to the current channel. This will allow them to join it even if it is a closed room. You can revoke this with /kick, /ban or /timeout.',
    'commands.closeroom': 'Close room',
    'commands.closeroom.help': 'Closes the current channel. This will only allow people you /invite to join it, and remove it from the rooms list.',
    'commands.openroom': 'Open room',
    'commands.openroom.help': 'Opens the current channel. This will allow anyone to join it, and let it be listed in the rooms list.',
    'commands.killchannel': 'Destroy room',
    'commands.killchannel.help': 'PERMANENTLY kills/destroys/removes the current room. All associated settings and prestige will be lost. Make sure this is what you want to do, you cannot undo it.',
    'commands.createchannel': 'Create official channel',
    'commands.createchannel.help': 'Creates an official, staff-moderated room.',
    'commands.createchannel.param0': 'Channel name',
    'commands.createchannel.param0.help': 'A name for the new official channel.',
    'commands.setmode': 'Set room mode',
    'commands.setmode.help': 'Set whether ads and/or chat are allowed in the current channel.',
    'commands.setmode.param0': 'Mode',
    'commands.setmode.param0.help': 'A valid room mode, namely "ads", "chat" or "both".',
    'commands.setdescription': 'Set room description',
    'commands.setdescription.help': 'Set the description for the current room.',
    'commands.setdescription.param0': 'Description',
    'commands.setdescription.param0.help': 'New description for the room. May contain up to 50,000 characters, and valid chat BBCode.',
    'commands.code': 'Copy channel code',
    'commands.code.help': 'Copies a BBCode link to the current channel into your clipboard. This can be pasted anywhere else on chat to render a link to this channel.',
    'commands.code.success': 'Channel code copied to your clipboard.',
    'commands.gkick': 'Chat kick',
    'commands.gkick.help': 'Removes a character from the chat. They are free to rejoin - use /gban or /gtimeout if you want to get rid of them for a longer period of time.',
    'commands.gban': 'Chat ban',
    'commands.gban.help': 'Bans a character from the chat. They will not be able to reconnect unless and until you undo this with /unban.',
    'commands.gunban': 'Chat unban',
    'commands.gunban.help': 'Unbans a character from the chat, allowing them to reconnect.',
    'commands.gtimeout': 'Chat timeout',
    'commands.gtimeout.help': 'Temporarily bans the given character from F-Chat. Mind the comma in the syntax!',
    'commands.gtimeout.param1': 'Duration',
    'commands.gtimeout.param1.help': 'The number of minutes to ban the character for.',
    'commands.gtimeout.param2': 'Reason',
    'commands.gtimeout.param2.help': 'The reason for the chat timeout.',
    'commands.gop': 'Promote to Chat OP',
    'commands.gop.help': 'Promotes a character to global chat OP.',
    'commands.gdeop': 'Demote from Chat OP',
    'commands.gdeop.help': 'Demotes a character from global chat OP.',
    'commands.scop': 'Promote to Super COP',
    'commands.scop.help': 'Promotes a character to super channel operator, making them an operator in all public channels.',
    'commands.scdeop': 'Demote from Super COP',
    'commands.scdeop.help': 'Demotes a character from super channel operator.',
    'commands.reloadconfig': 'Reload config',
    'commands.reloadconfig.help': 'Reload server-side config from disk.',
    'commands.reloadconfig.param0': 'Save?',
    'commands.reloadconfig.param0.help': 'Save ops, bans and channels to disk first.',
    'commands.xyzzy': 'Debug',
    'commands.xyzzy.help': 'Execute debug command on the server.',
    'commands.xyzzy.param0': 'Command',
    'commands.xyzzy.param0.help': 'The command to execute.',
    'commands.xyzzy.param1': 'Arguments',
    'commands.xyzzy.param1.help': 'The arguments to the command.',
    'status.online': 'Online',
    'status.away': 'Away',
    'status.busy': 'Busy',
    'status.looking': 'Looking',
    'status.dnd': 'Do Not Disturb',
    'status.idle': 'Idle',
    'status.offline': 'Offline',
    'status.crown': 'Rewarded',
    'importer.importGeneral': 'slimCat data has been detected on your computer.\nWould you like to import general settings?',
    'importer.importCharacter': `slimCat data for this character has been detected on your computer.
Would you like to import settings and logs?
This may take a while.
Any existing FChat 3.0 data for this character will be overwritten.`,
    'importer.importing': 'Importing data',
    'importer.importingNote': 'Importing logs. This may take a couple of minutes. Please do not close the application, even if it appears to hang for a while, as you may end up with incomplete logs.',
    'importer.error': 'There was an error importing your settings. The defaults will be used.',

    // RISING
    'rising.header.matching': 'Matching',
    'rising.header.preview': 'Preview',
    'rising.header.profile': 'Profile',
    'rising.header.misc': 'Misc',
    'rising.header.dangerZone': '⚠ Danger Zone! ⚠',
    'rising.header.visibility': 'Visibility',
    'rising.header.visibilityCaveat': 'Users will only be filtered once their kink data has been loaded (via opening their profile, mousing over their username, or viewing one of their ads).',
    'rising.header.ageMatch': 'Character Age Match',
    'rising.header.typeMatch': 'Type Match',
    'rising.header.exceptionList': 'Exception List',
    'rising.match.colorizeCompat': 'Colorize ads, profiles, and names of compatible and incompatible characters',
    'rising.match.showOnRightClick': 'Show quick match results in the right click character menu',
    'rising.match.showInSearch': 'Show quick match results in the search results',
    'settings.experiment.orientationMatching': 'Improve nonbinary<->nonbinary gender matching',
    'settings.experiment.orientationMatching.selectedInfo': '🚧 will be shown on experimental matches',
    'settings.match.relaxlength': 'Match with a wider range of post lengths',
    'settings.match.relaxlength.selectedInfo': 'In 0.7.3 post-length matching was reigned in; select this to match more broadly.',
    'rising.preview.showLinkPopup': 'Show a link/image preview when the mouse hovers over a link',
    'rising.preview.showCharacterPopup': 'Show a character preview when the mouse hovers over a character name',
    'rising.profile.compareKinks': 'Automatically compare kinks when viewing a character profile',
    'rising.profile.expandCustoms': 'Automatically expand custom kinks',
    'rising.misc.showUnread': 'Show unread note and offline message counts at the bottom right corner',
    'rising.misc.colorblind': 'Colorblind mode',
    'rising.misc.yourPortrait': 'Show character portrait by text input',
    'rising.misc.chatPortrait': 'Show character portrait with each message',
    'rising.misc.risingPortraits': 'Show high-quality ("Rising") portraits',
    'rising.theme.select': 'Override UI theme (for this character only)',
    'rising.theme.default': '(Use default theme)',
    // Need keys for themes, somehow.
    'rising.filter.warning': 'By activating filtering, you may no longer be able to see or receive all messages from F-Chat.',
    'rising.filter.adminWarning': 'It is up to you to make sure you are not hiding messages from moderators and admins.',
    'rising.filter.naToFriends': 'Filters do not apply to friends or bookmarked characters.',
    'rising.filter.beta': 'Beta version. Some of these features and behaviors may be removed or significantly changed in the future.',
    'rising.filter.hideAds': 'Hide ads from filtered characters',
    'rising.filter.hideSearch': 'Hide filtered characters from search results',
    'rising.filter.hideMembers': 'Hide filtered characters from channel members lists',
    'rising.filter.hidePubChat': 'Hide public channel messages from filtered characters',
    'rising.filter.hidePrivChat': 'Hide private channel messages from filtered characters',
    'rising.filter.hidePMs': 'Hide private messages (PMs) from filtered characters',
    'rising.filter.showIcon': 'Show filter icon on filtered characters',
    'rising.filter.automate': 'Send an automatic "no thank you" to filtered characters if they message you',
    'rising.filter.penalize': 'Penalize match scores for filtered characters',
    'rising.filter.reward': 'Increase match scores for non-filtered characters',
    'rising.age.match': 'Leave empty for no limit.',
    'rising.age.enter': 'Enter age',
    'rising.age.min': 'Characters younger than (years)',
    'rising.age.max': 'Characters older than (years)',
    'rising.exceptions': "Filters are not applied to these character names. Separate names with the Enter key, so there's only one character on each line. Friends and bookmarked characters bypass filtering automatically.",
    // Need keys for smartfilter entries.
    'rising.exceptions.ph': 'Enter names',

    'eicon.select': 'Select EIcon',
    'eicon.loading': 'Loading...',
    'eicon.search': 'Search eicons...',
    'eicon.favorites': 'Favorites',
    'eicon.expressions': 'Expressions',
    'eicon.soft': 'Soft',
    'eicon.sexual': 'Sexual',
    'eicon.speech': 'Speech bubbles',
    'eicon.symbols': 'Symbols',
    'eicon.memes': 'Memes',
    'eicon.random': 'Random',
    'eicon.refresh': `Fetch new eicons
Hold shift to refetch ALL eicons`,
    'eicon.thanks': 'Courtesy of ',
    'eicon.upload': 'Upload eicons',
    'eicon.favRemove': 'Remove from favorites',
    'eicon.favAdd': 'Add to favorites',

    'phelper.hook': 'Having problems with finding good matches?',
    'phelper.goal': 'The profile analyzer will identify if your profile could benefit from adjustments.',
    'phelper.working': 'Analyzing...',
    'phelper.recommendations': 'The profile analyzer recommends the following adjustments to your profile:',
    'phelper.heresHow': "Here's how",
    'phelper.good': 'Looking good!',
    'phelper.noImprovements': 'The profile analyzer could not find any improvement recommendations for your profile.',
    'phelper.addAvatar1': 'Add an avatar portrait',
    'phelper.addAvatar2': 'Profiles with an avatar portrait stand out in chats.',
    'phelper.unsupportedHQPotrait1': 'Unsupported high-quality portrait URL',
    'phelper.unsupportedHQPotrait2': 'High-quality portraits can only point to f-list.net, freeimages.host, e621.net, iili.io, imgur.com, or redgifs.com domains.',
    'phelper.addImage1': 'Add a profile image',
    'phelper.addImage2': 'Profiles with images are more attractive to other players.',
    'phelper.addImage3': 'Add more profile images',
    'phelper.addImage4': 'Profiles with images are more attractive – try to have at least 3 images in your profile.',
    'phelper.addInline1': 'Add an inline image',
    'phelper.addInline2': 'Profiles with inline images are more engaging to other players.',
    'phelper.addDesc1': 'Add a description',
    'phelper.addDesc2': 'Profiles with descriptions are more likely to draw attention from other players.',
    'phelper.addDesc3': 'Extend your description',
    'phelper.addDesc4': 'Long descriptions are more attractive to other players. Try expanding your description to at least 400 characters.',
    'phelper.badColors1': 'Fix color codes',
    'phelper.badColors2': "Some of the color codes in your profile won't render correctly in the F-Chat profile viewer. Your invalid codes are: {0}. \nThe only valid colors are: red, blue, white, yellow, pink, gray, green, orange, purple, black, brown, or cyan.",
    'phelper.addCustom1': 'Add custom kinks',
    'phelper.addCustom2': 'Custom kinks will help your profile stand out. Try adding at least 5 custom kinks.',
    'phelper.addCustom3': 'Add more custom kinks',
    'phelper.addCustom4': 'Players pay a lot of attention to custom kinks. Try adding at least 5 custom kinks.',
    'phelper.addCustom5': 'Add descriptions to custom kinks',
    'phelper.addCustom6': 'Some or all of your custom kinks are missing descriptions. Add descriptions to your custom kinks to attract more players.',
    'phelper.addKinks1': 'Add more kinks',
    'phelper.addKinks2': 'You should have at least 10 kinks for the matching algorithm to work well.',
    'phelper.addKinks3': "Add more '{0}' kinks",
    'phelper.addKinks4': "You should have at least {0} '{1}' kinks for the matching algorithm to work well.",
    'phelper.addAge1': 'Enter age',
    'phelper.addAge2': 'Specifying the age of your character will improve your matches with other players.',
    'phelper.addOrientation1': 'Enter sexual orientation',
    'phelper.addOrientation2': 'Specifying the sexual orientation of your character will improve your matches with other players.',
    'phelper.addSpecies1': 'Enter species',
    'phelper.addSpecies2': "Specifying the species of your character – even if it's 'human' – will improve your matches with other players.",
    'phelper.addPairPref1': 'Enter furry preference',
    'phelper.addPairPref2': 'Specifying whether you like to play with anthro characters will improve your matches with other players.',
    'phelper.addRole1': 'Enter sub/dom role',
    'phelper.addRole2': 'Specifying your preferred sub/dom role will improve your matches with other players.',
    'phelper.addPosition1': 'Enter position',
    'phelper.addPosition2': 'Specifying your preferred position (e.g. "top", "bottom") will improve your matches with other players.',
    'phelper.addPostLength1': 'Enter post length preference',
    'phelper.addPostLength2': 'Specifying your post length preference will improve your matches with other players.',
    'phelper.addBodyType1': 'Enter body type',
    'phelper.addBodyType2': "Specifying your character's body type will improve your matches with other players.",
    'phelper.addGender1': 'Enter gender',
    'phelper.addGender2': "Specifying your character's gender will help matching you with other players",
    'phelper.mismatch': 'Inconsistent kink',
    'phelper.mismatchFurriesOnly': 'Your "furries-only" profile has a positive "humans" kink. If you are open to playing with humans, consider updating your preference from "furries only" to "furs and humans".',
    'phelper.mismatchHumansOnly': 'Your "humans-only" profile has a positive "furry" kink ({0}). If you are open to playing with anthros, consider updating your preference from "humans only" to "furs and humans"',
    'phelper.addSpeciesPref1': 'Add preferred species',
    'phelper.addSpeciesPref2': 'Specifying which anthro species you like (e.g. "equines", or "canines") in your kinks can improve your matches.',
};

export default function l(key: string, ...args: (string | number)[]): string {
    let i = args.length;
    let str = strings[key];
    if(str === undefined) {
        if(process.env.NODE_ENV !== 'production') throw new Error(`String ${key} does not exist.`);
        return '';
    }
    while(i-- > 0)
        str = str.replace(new RegExp(`\\{${i}\\}`, 'igm'), args[i].toString());
    return str;
}
